import { cn } from '@/utils/utils';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'h-screen bg-white p-5')}>
        {children}
      </body>
    </html>
  );
}
